### PR TITLE
add send subcommand to send a message from CLI

### LINKED ISSUE #20: add CLI to send messages without user interaction
useful to send messages using scripts, etc.

### PR DESCRIPTION
**Pull request by adbenitez**
close #20

### CODE REVIEW

**Comment by dotlambda** [comment]
How do I find out the chat id of a group? That might actually be a good thing to mention in `--help`.

**Comment by adbenitez** [comment]
for now it is only for direct chats:
```
delta send --chat friend@example.com "hello dude!"
```

I plan to add an option to list chats and their id before releasing the next version :)

currently working in improving the CLI before adding more commands that is why have not been added yet

**Comment by adbenitez** [comment]
also plan to add more options than only text messages, so people can send files, and even control message view type to send stickers etc

**Comment by adbenitez** [comment]
> I plan to add an option to list chats and their id before releasing the next version :)

maybe also a `/id` command inside app to get chat id

**Comment by adbenitez** [comment]
done, you can list all ids using `delta list` CLI or get current chat id with /id command inside TUI

**Pull request merged**
